[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid
user=root

[program:xmrig-proxy]
command=/usr/local/bin/xmrig-proxy --config=/app/config.json
directory=/app
autostart=true
autorestart=true
startretries=5
startsecs=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=1

[program:ws-proxy]
command=node /app/proxy.js
directory=/app
autostart=true
autorestart=true
startretries=5
startsecs=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=XMRIG_HOST="127.0.0.1",XMRIG_PORT="3333",STATS_PORT="9000"
priority=2
